Ns/UI enchancement
dimagi/commcare-connect pull request #268
Opened 2024-02-09 15:02 UTC by cws1121

1. Bootswatch Skin Addition: Implemented a new Bootswatch skin to enhance the overall visual appeal and consistency of the UI.
3. Table Design Enhancement: Improved table design for better responsiveness across different devices, ensuring a seamless user experience.
5. Icon Integration: Integrated icons strategically throughout the UI to improve usability and visual communication.
7. Other UI Tweaks: Made various small tweaks and adjustments to enhance the overall user interface

2024-02-09 17:17 UTC, pxwxnvermx commented on commcare_connect/templates/opportunity/user_learn_progress.html
> +          The Opportunity
This can be replaced with the suggestion to render the opportunity name.
```suggestion
          {{ object.opportunity.name }}
```

2024-02-12 21:25 UTC, calellowitz requested changes
Thanks for doing all this. I clicked around on staging, and generally this all looks good. I left a couple questions on the code, but the only real feedback I have is that a number of the areas have very low contrast, and are a bit difficult to see. I have attached screenshots of all the places I saw this. It would be great if those could be made easier to read.

![Screenshot from 2024-02-12 15-53-29](https://github.com/dimagi/commcare-connect/assets/6844721/d18a41c0-33fd-4b5f-a33c-5786159c0dc0)
![Screenshot from 2024-02-12 15-43-31](https://github.com/dimagi/commcare-connect/assets/6844721/69c367f0-42fd-4103-983b-0803e2bf5791)
![Screenshot from 2024-02-12 15-42-57](https://github.com/dimagi/commcare-connect/assets/6844721/c290192c-2678-447d-a825-7cf1258376c6)
![Screenshot from 2024-02-12 15-42-46](https://github.com/dimagi/commcare-connect/assets/6844721/e9cb18b8-a68a-4d26-8b8f-47ab27b789a9)

2024-02-12 21:25 UTC, calellowitz commented on commcare_connect/opportunity/models.py
> +        return 10  # Example fixed value
This can be `self.total_budget / self.budget_per_visit`

2024-02-12 21:25 UTC, calellowitz commented on commcare_connect/templates/opportunity/add_visits_existing_users.html
> +  <nav class="mt-2 small" aria-label="breadcrumb">
A lot of these pages just add breadcrumbs. Is there a way to add breadcrumbs to the base template so we don't have to add them each time?

2024-02-12 22:06 UTC, calellowitz commented
I found a few other places with low contrast, specifically where we use white text on an orange background.

On the edit button of the opportunity list
![Screenshot from 2024-02-12 17-05-22](https://github.com/dimagi/commcare-connect/assets/6844721/fd9d42db-8ad0-4976-aa49-bae0e3a5d7d2)

The warnings in the user visit list
![Screenshot from 2024-02-12 17-03-20](https://github.com/dimagi/commcare-connect/assets/6844721/d65aca80-1dcf-4cc7-a0d0-465b70e31cdc)

2024-02-14 15:58 UTC, calellowitz approved these changes

2024-02-14 15:58 UTC, merged